### ISSUE TITLE
Adding new sercom serial port

### ISSUE THREAD

**Issue by applemuncy** [ElectronicCats/ArduinoCore-samd#5]
I've been working at using this to program a Rak4260-dev board using the bastwan as selected board in the Arduino IDE.
As far as I can tell the pins 32 and 33 on the RAK4260 must be hardwired to the ch341-uart converter on the RAK5005 base board.

pin 32 -> PA04
pin 33 -> PA05

But digging deep into core/arduino libraries it seem this library does its own thing : )
as far as pinPeripheral ( xxx ,PIO_SERCOM_ALT) is not supported. How do you handle creating a serial port on sercom alternate pins?

I see reference in the documentation to a  Serial Config Menu but must have been dropped?

**Comment by applemuncy** [comment]
OK. I have managed to add another serial port by edits to pin descriptions of PORTA, 4 and 5 in variants.cpp thus have 3 serial ports to work with.

On going I'm wondering about the various board coming out with  RAK4260 modules could be included in this great board manager?

I'll close this issue in a week or so.

**Comment by sabas1080** [comment]
Hi @applemuncy 

Bastwan uses native USB, so serial is not active. Other boards with RAK4260 can be included in this core

**Comment by applemuncy** [comment]
Greetings Sabas,
Thank you for your response and all your contributions to free software.
So to be honest I'm just an old hacker that looses interest after I get something working just well enough to use for my own purpose.
And some people believe the design of the RAK4260-DEV board is flawed and will probably (in my opinion) be changed before it becomes an official core board for the WisBlock system. So for the time being I don't see a reason to make it a separate choice in the board menu.  
I think I will put a post in the forum.rakwireless.com about the changes to vatiant.h/cpp file to achieve two USB and one tx/rx ports.  I do not understand yet what all the six different choices do for configuring USB for the Bastwan.

RakWireless has a really world class programmer working on the RAK4630 WisBlock.  In my opinion they would do well to put either you or Edwardo on their payroll to do the same for the RAK4260.

**Comment by sabas1080** [comment]
@applemuncy thank you for your comments

USB settings are to free USB or save memory
