### ISSUE TITLE
Check please if SPI1 is really correct defined?

### ISSUE THREAD

**Issue by bobricius** [ElectronicCats/ArduinoCore-samd#6]
Hi,
can please anybody check SPI1 definition ?

Tring connect display
#define TFT_CS        13// chip select
#define TFT_DC        1 // Display data/command select
#define TFT_BACKLIGHT 0 // Display backlight pin
#define TFT_MOSI 14  // Data out
#define TFT_SCLK 16  // Clock out

this working 
Adafruit_ST7789 tft = Adafruit_ST7789(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST);

but this not working
Adafruit_ST7789 tft = Adafruit_ST7789(&SPI1, TFT_CS, TFT_DC, TFT_RST);

not swapped miso/mosi ? I try change in variant.h but not success 

Thanks

**Comment by bobricius** [comment]
yes, mosi / miso swapped but on my board, I used different library symbol.
Thanks for sharing your core!

**Comment by sabas1080** [comment]
@bobricius thanks!
